### ISSUE TITLE
Allow excluding some of the checks?

### ISSUE THREAD

**Issue by tygre-chingu** [shred/patchwork#4]
Hi!
I'm using PatchWork on my development Amiga and I noticed a lot of "hit" with Miami Airport (ioReplyPort not initialized) and graphics.library (RectFill max must be >= min). They kind of "clutter" my console and there's nothing much I can do about them, so I wonder if PatchWork could have an option to silence some checks?
Thanks for this great tool!

**Comment by tygre-chingu** [comment]
Hi and thanks for your quick reply :)

Actually, I thought about exactly the same thing after posting but the other way around: maybe we could have an option to monitor a specific task name?

I'm not sure why I'm getting these hits with graphics.library, they seem to happen when I iconify some windows, I should make more tests without patches: maybe one of the patch that I installed actually cause this problem (like MCP)?

**Comment by shred** [comment]
Done. :smile: There is a new option `TASKNAME` now, which limits the output to hits caused by tasks with the given name.

About `graphics.library`, it can also be caused by heavily patched systems like AmigaOS 3.2 with an older hardware ROM version. I guess there is not much I can do about that.

The change is available in PatchWork V1.1. You will find it in the release section here, or in the Aminet tomorrow.

Thank you for the feature request!

**Comment by tygre-chingu** [comment]
Wow, thanks a lot! :-)
I'll download and install it immediately... I'm also going to track the patch that cause all these "hits" in graphics.library...

**Comment by tygre-chingu** [comment]
PS. I found what caused all these "hits" in graphics.library: the Cubic IDE. When it runs, as soon as something happens that requires it to refresh its window, there are hits. For example, moving a window on top of Cubic IDE will cause "hits". Moving the same window *next* to Cubic IDE doesn't cause any hit. When Cubic IDE doesn't run, there are no such hits at all. Maybe GoldEd or Cubic IDE itself hijack the refresh?
